CREATE TABLE IF NOT EXISTS doctors (
  id SERIAL PRIMARY KEY,
  sno INTEGER,
  city TEXT,
  area TEXT,
  subarea TEXT,
  doctor TEXT,
  qual TEXT,
  remarks TEXT
);

INSERT INTO doctors (sno, city, area, subarea, doctor, qual, remarks) VALUES
(1, 'Indore', 'Sapna Sangeeta', 'Sapna Sangeeta', 'Dr. Suyash Gupta', '', ''),
(2, 'Indore', 'Sapna Sangeeta', 'Sapna Sangeeta', 'Dr. Vijay Nichani', '', ''),
(3, 'Indore', 'Sapna Sangeeta', 'Sapna Sangeeta', 'Dr. Shyam Agrawal', '', ''),
(4, 'Indore', 'Sapna Sangeeta', 'Sapna Sangeeta', 'Dr. Pramod Sharma', '', ''),
(5, 'Indore', 'Sapna Sangeeta', 'Sapna Sangeeta', 'Dr. Geeta Sharma', '', ''),
(6, 'Indore', 'Sapna Sangeeta', 'Sapna Sangeeta', 'Dr. Mamata Garg', '', ''),
(7, 'Indore', 'Sapna Sangeeta', 'Sapna Sangeeta', 'Dr. P. Gupta', '', ''),
(8, 'Indore', 'Sapna Sangeeta', 'Sapna Sangeeta', 'Dr. Sushil Agrawal', '', ''),
(9, 'Indore', 'Sapna Sangeeta', 'Sapna Sangeeta', 'Dr. M. K. Sharma', '', ''),
(10, 'Indore', 'Sapna Sangeeta', 'Sapna Sangeeta', 'Dr. Umesh Masand', '', ''),
(11, 'Indore', 'Khatiwala Tank', 'Khatiwala Tank', 'Dr. Qurban Hussain', '', ''),
(12, 'Indore', 'Khatiwala Tank', 'Khatiwala Tank', 'Dr. Z. A. Modiwala', '', ''),
(13, 'Indore', 'Khatiwala Tank', 'Khatiwala Tank', 'Dr. Q. A. Modiwala', '', ''),
(14, 'Indore', 'Khatiwala Tank', 'Khatiwala Tank', 'Dr. Kailash Saluja', '', ''),
(15, 'Indore', 'Khatiwala Tank', 'Khatiwala Tank', 'Dr. Vijay Paryani', '', ''),
(16, 'Indore', 'Khatiwala Tank', 'Khatiwala Tank', 'Dr. S. C. Hablani', '', ''),
(17, 'Indore', 'Khatiwala Tank', 'Khatiwala Tank', 'Dr. Saifi Rampurawala', '', ''),
(18, 'Indore', 'Nayta Mundla', 'Nayta Mundla', 'Dr. Umesh Sharma', '', ''),
(19, 'Indore', 'Nayta Mundla', 'Nayta Mundla', 'Dr. Mayank Patidar', '', ''),
(20, 'Indore', 'Nayta Mundla', 'Nayta Mundla', 'Dr. Manoj Mallik', '', ''),
(21, 'Indore', 'Nayta Mundla', 'Nayta Mundla', 'Dr. Aanand Badol', '', ''),
(22, 'Indore', 'Nayta Mundla', 'Nayta Mundla', 'Dr. Imran Ansari', '', ''),
(23, 'Indore', 'Nayta Mundla', 'Nayta Mundla', 'Dr. Javed Patel', '', ''),
(24, 'Indore', 'Nayta Mundla', 'Nayta Mundla', 'Dr. Arun Prajapat', '', ''),
(25, 'Indore', 'Nayta Mundla', 'Nayta Mundla', 'Dr. Qamar Husain', '', ''),
(26, 'Indore', 'Nayta Mundla', 'Nayta Mundla', 'Dr. Anas Husain Ansari', '', ''),
(27, 'Indore', 'Ganesh Nagar', 'Ganesh Nagar', 'Dr. Om Gurjar', '', ''),
(28, 'Indore', 'Ganesh Nagar', 'Ganesh Nagar', 'Dr. Akalakh Khan', '', ''),
(29, 'Indore', 'Ganesh Nagar', 'Ganesh Nagar', 'Dr. Kamlesh Jaat', '', ''),
(30, 'Indore', 'Ganesh Nagar', 'Ganesh Nagar', 'Dr. Mahesh Patil', '', ''),
(31, 'Indore', 'Ganesh Nagar', 'Ganesh Nagar', 'Dr. Pankaj Gupta', '', ''),
(32, 'Indore', 'Ganesh Nagar', 'Ganesh Nagar', 'Dr. Irfan Khan', '', ''),
(33, 'Indore', 'Ganesh Nagar', 'Ganesh Nagar', 'Dr. Vivek Sharma', '', ''),
(34, 'Harda', 'Harda/Timarni', 'Timarni', 'Dr. Kesri Prasad', 'MBBS', ''),
(35, 'Harda', 'Harda/Timarni', 'Timarni', 'Dr. Pranay Raghuvanshi', 'MD', ''),
(36, 'Harda', 'Harda/Timarni', 'Harda', 'Dr. Virendra Agrawal', 'MD', ''),
(37, 'Harda', 'Harda/Timarni', 'Harda', 'Dr. Bharat Katkar', 'MS', ''),
(38, 'Harda', 'Harda/Timarni', 'Harda', 'Dr. Brajesh Heda', 'MS', ''),
(39, 'Harda', 'Harda/Timarni', 'Harda', 'Dr. Kailash Singhal', 'MD', ''),
(40, 'Harda', 'Harda/Timarni', 'Harda', 'Dr. Sangeeta Bankey', 'MS', ''),
(41, 'Harda', 'Harda/Timarni', 'Harda', 'Dr. Ram Dogane', 'D.ortho.', ''),
(42, 'Harda', 'Harda/Timarni', 'Harda', 'Dr. Sunil Gurjar', 'MS', ''),
(43, 'Harda', 'Harda/Timarni', 'Harda', 'Dr. Gambhir Patel', 'MS', ''),
(44, 'Harda', 'Harda/Timarni', 'Harda', 'Dr. Arjun Mohe', 'MS', ''),
(45, 'Harda', 'Harda/Timarni', 'Harda', 'Dr. Prerna Dhamnani', 'DGO', ''),
(46, 'Harda', 'Harda/Timarni', 'Harda', 'Dr. Sandeep Evane', 'MS', ''),
(47, 'Harda', 'Harda/Timarni', 'Harda', 'Dr. Rajesh Patidar', 'MD', ''),
(48, 'Indore', 'Juni Indore', 'Juni Indore', 'Dr. Nafisa Mahir', '', ''),
(49, 'Indore', 'Juni Indore', 'Juni Indore', 'Dr. Himanshu Dagour', '', ''),
(50, 'Indore', 'Juni Indore', 'Juni Indore', 'Dr. Sourabh Rathore', '', ''),
(51, 'Indore', 'Juni Indore', 'Juni Indore', 'Dr. B. Mandloi', '', ''),
(52, 'Indore', 'Juni Indore', 'Juni Indore', 'Dr. Subhash Chavla', '', ''),
(53, 'Indore', 'Juni Indore', 'Juni Indore', 'Dr. O. P. Kankane', '', ''),
(54, 'Khategaon', 'Khategaon/Kannaud/Katafod/Satwas', 'Katafod', 'Dr. Aanand Malwiya', '', ''),
(55, 'Khategaon', 'Khategaon/Kannaud/Katafod/Satwas', 'Katafod', 'Dr. B. P. Malwiya', '', ''),
(56, 'Khategaon', 'Khategaon/Kannaud/Katafod/Satwas', 'Katafod', 'Dr. Harsh Wardhan Rana', '', 'Gov.hospital'),
(57, 'Khategaon', 'Khategaon/Kannaud/Katafod/Satwas', 'Satwas', 'Dr. Iqbal Khan', '', 'Satwas'),
(58, 'Khategaon', 'Khategaon/Kannaud/Katafod/Satwas', 'Satwas', 'Dr. Manoj Yadav', '', ''),
(59, 'Khategaon', 'Khategaon/Kannaud/Katafod/Satwas', 'Satwas', 'Dr. B. S. Yadav', '', ''),
(60, 'Khategaon', 'Khategaon/Kannaud/Katafod/Satwas', 'Satwas', 'Dr. Shabadar Khan', '', 'Pulse hospital'),
(61, 'Khategaon', 'Khategaon/Kannaud/Katafod/Satwas', 'Khategaon', 'Dr. R. N. Yadav', '', 'Khategaon'),
(62, 'Khategaon', 'Khategaon/Kannaud/Katafod/Satwas', 'Khategaon', 'Dr. Ashwin Yadav', '', ''),
(63, 'Khategaon', 'Khategaon/Kannaud/Katafod/Satwas', 'Khategaon', 'Dr. Mukesh Yadav', '', ''),
(64, 'Khategaon', 'Khategaon/Kannaud/Katafod/Satwas', 'Khategaon', 'Dr. Lekharaj', 'MBBS', 'Govt.hospital'),
(65, 'Khategaon', 'Khategaon/Kannaud/Katafod/Satwas', 'Kannod', 'Dr. Manisha Meena', 'MS obg', 'Kannod'),
(66, 'Khategaon', 'Khategaon/Kannaud/Katafod/Satwas', 'Kannod', 'Dr. Alfiya Qureshi', '', ''),
(67, 'Khategaon', 'Khategaon/Kannaud/Katafod/Satwas', 'Kannod', 'Dr. Mo. Javed Khan', '', ''),
(68, 'Khategaon', 'Khategaon/Kannaud/Katafod/Satwas', 'Kannod', 'Dr. Lokesh Meena', '', ''),
(69, 'Indore', 'Bangali Chauraha', 'Bangali Chauraha', 'Dr. Komal Shah', '', ''),
(70, 'Indore', 'Bangali Chauraha', 'Bangali Chauraha', 'Dr. Prashant Triwedi', '', ''),
(71, 'Indore', 'Bangali Chauraha', 'Bangali Chauraha', 'Dr. Sachin MoryaR.', '', ''),
(72, 'Indore', 'Bangali Chauraha', 'Bangali Chauraha', 'Dr. R. Amlani', '', ''),
(73, 'Indore', 'Bangali Chauraha', 'Bangali Chauraha', 'Dr. Aashish Rathore', '', ''),
(74, 'Indore', 'Bangali Chauraha', 'Bangali Chauraha', 'Dr. M. K. Sharma', '', ''),
(75, 'Hatpipliya/Bagli', 'Hatpipliya/Bagli/Chapda', 'Chapda', 'Dr. J. S. Kachhwahe', '', ''),
(76, 'Hatpipliya/Bagli', 'Hatpipliya/Bagli/Chapda', 'Chapda', 'Dr. J. C. Yadav', '', ''),
(77, 'Hatpipliya/Bagli', 'Hatpipliya/Bagli/Chapda', 'Chapda', 'Dr. Vishal Rathore', '', ''),
(78, 'Hatpipliya/Bagli', 'Hatpipliya/Bagli/Chapda', 'Chapda', 'Dr. Anil Dhangar', '', ''),
(79, 'Hatpipliya/Bagli', 'Hatpipliya/Bagli/Chapda', 'Chapda', 'Dr. Dharmendra Soulnki', '', 'R&R hospital'),
(80, 'Hatpipliya/Bagli', 'Hatpipliya/Bagli/Chapda', 'Chapda', 'Dr. Anil Kanthal', '', ''),
(81, 'Hatpipliya/Bagli', 'Hatpipliya/Bagli/Chapda', 'Hatpipliya', 'Dr. K. K. Datta', '', ''),
(82, 'Hatpipliya/Bagli', 'Hatpipliya/Bagli/Chapda', 'Hatpipliya', 'Dr. S. R. Datta', '', ''),
(83, 'Hatpipliya/Bagli', 'Hatpipliya/Bagli/Chapda', 'Hatpipliya', 'Dr. N. K. Patni', '', 'Vishal. Endo'),
(84, 'Hatpipliya/Bagli', 'Hatpipliya/Bagli/Chapda', 'Hatpipliya', 'Dr. S. P. Pathak', '', ''),
(85, 'Hatpipliya/Bagli', 'Hatpipliya/Bagli/Chapda', 'Hatpipliya', 'Vijay Nagar (Note: written in list)', '', ''),
(86, 'Hatpipliya/Bagli', 'Hatpipliya/Bagli/Chapda', 'Hatpipliya', 'Dr. Mahipal Rana', '', ''),
(87, 'Hatpipliya/Bagli', 'Hatpipliya/Bagli/Chapda', 'Hatpipliya', 'Dr. Jeevan Yadav', '', ''),
(88, 'Hatpipliya/Bagli', 'Hatpipliya/Bagli/Chapda', 'Hatpipliya', 'Dr. Mustak Khan', '', ''),
(89, 'Rao', 'Rao', 'Rao', 'Dr. Monika Shilpi', '', ''),
(90, 'Rao', 'Rao', 'Rao', 'Dr. Sarita Chouhan', '', ''),
(91, 'Rao', 'Rao', 'Rao', 'Dr. Amit Dave', '', ''),
(92, 'Rao', 'Rao', 'Rao', 'Dr. Ram Patidar', '', ''),
(93, 'Rao', 'Rao', 'Rao', 'Dr. K. K. Paliwal', '', ''),
(94, 'Rao', 'Rao', 'Rao', 'Dr. J. K. Naganpuriya', '', ''),
(95, 'Rao', 'Rao', 'Rao', 'Dr. Devendra Mishra', '', ''),
(96, 'Rao', 'Rao', 'Rao', 'Dr. Sanjay Birla', '', ''),
(97, 'Rao', 'Rao', 'Rao', 'Dr. Deepika Rane', '', ''),
(98, 'Rao', 'Rao', 'Rao', 'Dr. Priyanka Vaskalle', '', ''),
(99, 'Indore', 'Tejpur Gadbadi', 'Tejpur Gadbadi', 'Dr. Sourabh Biswas', '', ''),
(100, 'Indore', 'Tejpur Gadbadi', 'Tejpur Gadbadi', 'Dr. Naresh Yadav', '', ''),
(101, 'Indore', 'Tejpur Gadbadi', 'Tejpur Gadbadi', 'Dr. R. Soni', '', ''),
(102, 'Indore', 'Tejpur Gadbadi', 'Tejpur Gadbadi', 'Dr. Ibrahim Boharawala', '', ''),
(103, 'Indore', 'Tejpur Gadbadi', 'Tejpur Gadbadi', 'Dr. Rajendra Yadav', '', ''),
(104, 'Dhamnod/Manawar', 'Dhamnod/Manawar/Khalghat/Dharampuri', 'Dhamnod', 'Dr. Bharti Patidar', '', ''),
(105, 'Dhamnod/Manawar', 'Dhamnod/Manawar/Khalghat/Dharampuri', 'Dhamnod', 'Dr. Vikki Patidar', '', ''),
(106, 'Dhamnod/Manawar', 'Dhamnod/Manawar/Khalghat/Dharampuri', 'Khalgat', 'Dr. P. Joshi', '', ''),
(107, 'Dhamnod/Manawar', 'Dhamnod/Manawar/Khalghat/Dharampuri', 'Dharampuri', 'Dr. Lucky Jayaswal', 'MD', ''),
(108, 'Dhamnod/Manawar', 'Dhamnod/Manawar/Khalghat/Dharampuri', 'Dharampuri', 'Dr. Shubham Yadav', '', ''),
(109, 'Dhamnod/Manawar', 'Dhamnod/Manawar/Khalghat/Dharampuri', 'Dharampuri', 'Dr. Piyush Chouhan', '', ''),
(110, 'Dhamnod/Manawar', 'Dhamnod/Manawar/Khalghat/Dharampuri', 'Dharampuri', 'Dr. Shubham Soulanki', '', ''),
(111, 'Dhamnod/Manawar', 'Dhamnod/Manawar/Khalghat/Dharampuri', 'Dharampuri', 'Dr. R. S. Pawar', 'MD', ''),
(112, 'Dhamnod/Manawar', 'Dhamnod/Manawar/Khalghat/Dharampuri', 'Dharampuri', 'Dr. Mitali Chouhan', 'MS', ''),
(113, 'Dhamnod/Manawar', 'Dhamnod/Manawar/Khalghat/Dharampuri', 'Manawar', 'Dr. Sunil Desai', '', ''),
(114, 'Dhamnod/Manawar', 'Dhamnod/Manawar/Khalghat/Dharampuri', 'Manawar', 'Dr. Sanjay Muvel', '', ''),
(115, 'Dhamnod/Manawar', 'Dhamnod/Manawar/Khalghat/Dharampuri', 'Manawar', 'Dr. Kuldeep Jouhar', 'MD', ''),
(116, 'Dhamnod/Manawar', 'Dhamnod/Manawar/Khalghat/Dharampuri', 'Manawar', 'Dr. Sachin Patidar', '', ''),
(117, 'Dhamnod/Manawar', 'Dhamnod/Manawar/Khalghat/Dharampuri', 'Manawar', 'Dr. K. C. Rane', '', ''),
(118, 'Indore', 'Annapurna', 'Annapurna', 'Dr. Abhishek Sharma', 'MD', ''),
(119, 'Indore', 'Annapurna', 'Annapurna', 'Dr. Anil Budhwani', 'MBBS', ''),
(120, 'Indore', 'Annapurna', 'Annapurna', 'Dr. V. D. Sharma', 'MD', ''),
(121, 'Indore', 'Annapurna', 'Annapurna', 'Dr. Rupesh Agrawal', 'DTCD', ''),
(122, 'Indore', 'Annapurna', 'Annapurna', 'Dr. Bhaskar Tiwari', '', ''),
(123, 'Indore', 'Annapurna', 'Annapurna', 'Dr. A. Pancholi', '', ''),
(124, 'Barwani', 'Barwani/Dawana', 'Dawana', 'Dr. Mehul Mukati', '', ''),
(125, 'Barwani', 'Barwani/Dawana', 'Dawana', 'Dr. Harsh Joshi', '', ''),
(126, 'Barwani', 'Barwani/Dawana', 'Badwani', 'Dr. Aashish Yadav', '', ''),
(127, 'Barwani', 'Barwani/Dawana', 'Badwani', 'Dr. Manoj Gurjar', '', ''),
(128, 'Barwani', 'Barwani/Dawana', 'Badwani', 'Dr. Rajesh Jain', '', ''),
(129, 'Barwani', 'Barwani/Dawana', 'Badwani', 'Dr. K. C. Mandloi', '', ''),
(130, 'Barwani', 'Barwani/Dawana', 'Badwani', 'Dr. Sandeep Gupta', '', ''),
(131, 'Barwani', 'Barwani/Dawana', 'Badwani', 'Dr. Rakesh Patidar', '', ''),
(132, 'Barwani', 'Barwani/Dawana', 'Badwani', 'Dr. B. K. Saxsena', '', ''),
(133, 'Barwani', 'Barwani/Dawana', 'Badwani', 'Dr. Deepak Awasiya', '', ''),
(134, 'Barwani', 'Barwani/Dawana', 'Badwani', 'Dr. Rajnish Patidar', '', ''),
(135, 'Barwani', 'Barwani/Dawana', 'Badwani', 'Dr. M. S. Soulanki', '', ''),
(136, 'Barwani', 'Barwani/Dawana', 'Badwani', 'Dr. Anil Singh Jamod', 'MS', ''),
(137, 'Barwani', 'Barwani/Dawana', 'Badwani', 'Dr. Avinash Barfa', '', ''),
(138, 'Pithampur', 'Pithampur/Sagour Kuti/ Kali Billod', 'Pithampur', 'Dr. Rakesh Asolia', 'CT', ''),
(139, 'Pithampur', 'Pithampur/Sagour Kuti/ Kali Billod', 'Pithampur', 'Dr. Akhilesh Rathore', '', ''),
(140, 'Pithampur', 'Pithampur/Sagour Kuti/ Kali Billod', 'Pithampur', 'Dr. Sawan Patidar', '', ''),
(141, 'Pithampur', 'Pithampur/Sagour Kuti/ Kali Billod', 'Pithampur', 'Dr. Ashwini Sinha', '', ''),
(142, 'Pithampur', 'Pithampur/Sagour Kuti/ Kali Billod', 'Pithampur', 'Dr. Deepak Kourav', '', ''),
(143, 'Pithampur', 'Pithampur/Sagour Kuti/ Kali Billod', 'Sagour Kuti', 'Dr. Sharad Patel', '', ''),
(144, 'Pithampur', 'Pithampur/Sagour Kuti/ Kali Billod', 'Sagour Kuti', 'Dr. Sourabh Parmar', '', ''),
(145, 'Pithampur', 'Pithampur/Sagour Kuti/ Kali Billod', 'Sagour Kuti', 'Dr. B. K. Bhandari', '', ''),
(146, 'Pithampur', 'Pithampur/Sagour Kuti/ Kali Billod', 'Sagour Kuti', 'Dr. Vikas Bhandari', '', ''),
(147, 'Pithampur', 'Pithampur/Sagour Kuti/ Kali Billod', 'Sagour Kuti', 'Dr. Aashish Mishra', '', 'A4. Hospital'),
(148, 'Pithampur', 'Pithampur/Sagour Kuti/ Kali Billod', 'Kali Billod', 'Dr. Aasha Pavaia', '', ''),
(149, 'Pithampur', 'Pithampur/Sagour Kuti/ Kali Billod', 'Kali Billod', 'Devansh NH (Note: written in list)', '', ''),
(150, 'Indore', 'Musakhedi', 'Musakhedi', 'Dr. L. N. Jat', '', ''),
(151, 'Indore', 'Musakhedi', 'Musakhedi', 'Dr. R. R. Gurjar', '', ''),
(152, 'Indore', 'Musakhedi', 'Musakhedi', 'Dr. Piyush Malwia', '', ''),
(153, 'Indore', 'Musakhedi', 'Musakhedi', 'Dr. Rajesh Yadav', '', ''),
(154, 'Indore', 'Musakhedi', 'Musakhedi', 'Dr. Kamal Gurjar', '', ''),
(155, 'Indore', 'Musakhedi', 'Musakhedi', 'Dr. Vimla Mehata', '', ''),
(156, 'Indore', 'Musakhedi', 'Musakhedi', 'Dr. S. K. Chouhan', '', ''),
(157, 'Indore', 'Musakhedi', 'Musakhedi', 'Dr. Javed Ali', '', ''),
(158, 'Indore', 'Musakhedi', 'Musakhedi', 'Dr. Tahira Siddiqui', '', ''),
(159, 'Indore', 'Kampel', 'Kampel', 'Dr. Nikhilesh Choudhary', '', ''),
(160, 'Indore', 'Kampel', 'Kampel', 'Dr. J. Pindoriya', '', ''),
(161, 'Indore', 'Kampel', 'Kampel', 'Dr. Tushar Vishwas', '', ''),
(162, 'Indore', 'Kampel', 'Kampel', 'Dr. Deenesh Dangi', '', ''),
(163, 'Indore', 'Kampel', 'Kampel', 'Dr. Sohan Rajput', '', ''),
(164, 'Indore', 'Kampel', 'Kampel', 'Dr. Mukesh Jat', '', ''),
(165, 'Indore', 'Kampel', 'Kampel', 'Dr. Tajshekh', '', ''),
(166, 'Indore', 'Kampel', 'Kampel', 'Dr. R. P. Chouhan', '', ''),
(167, 'Dhamnod/Dharampuri', 'Dhamnod/Dharampuri/Mandleshwar/Maheshwar', 'Dhamnod', 'Dr. Vikki Patidar', '', ''),
(168, 'Dhamnod/Dharampuri', 'Dhamnod/Dharampuri/Mandleshwar/Maheshwar', 'Dhamnod', 'Dr. Sumit Sharma', '', ''),
(169, 'Dhamnod/Dharampuri', 'Dhamnod/Dharampuri/Mandleshwar/Maheshwar', 'Dhamnod', 'Dr. Y. K. Sharma', '', ''),
(170, 'Dhamnod/Dharampuri', 'Dhamnod/Dharampuri/Mandleshwar/Maheshwar', 'Dharampuri', 'Dr. Monika Baghel', '', ''),
(171, 'Dhamnod/Dharampuri', 'Dhamnod/Dharampuri/Mandleshwar/Maheshwar', 'Dhamnod', 'Dr. R. K. Patidar', '', ''),
(172, 'Dhamnod/Dharampuri', 'Dhamnod/Dharampuri/Mandleshwar/Maheshwar', 'Dhamnod', 'Dr. Priti Patidar', '', ''),
(173, 'Dhamnod/Dharampuri', 'Dhamnod/Dharampuri/Mandleshwar/Maheshwar', 'Dhamnod', 'Dr. Ankur Kumbhakar', '', ''),
(174, 'Dhamnod/Dharampuri', 'Dhamnod/Dharampuri/Mandleshwar/Maheshwar', 'Dhamnod', 'Dr. Rashmi Soulanki', 'DGO', ''),
(175, 'Dhamnod/Dharampuri', 'Dhamnod/Dharampuri/Mandleshwar/Maheshwar', 'Dhamnod', 'Dr. Monika Chouhan', 'MS obg', ''),
(176, 'Dhamnod/Dharampuri', 'Dhamnod/Dharampuri/Mandleshwar/Maheshwar', 'Mandleshwar', 'Dr. Kamal Jadhav', '', ''),
(177, 'Dhamnod/Dharampuri', 'Dhamnod/Dharampuri/Mandleshwar/Maheshwar', 'Mandleshwar', 'Dr. Prasanna Jain', '', ''),
(178, 'Dhamnod/Dharampuri', 'Dhamnod/Dharampuri/Mandleshwar/Maheshwar', 'Mandleshwar', 'Dr. Sonu Ozha', '', ''),
(179, 'Dhamnod/Dharampuri', 'Dhamnod/Dharampuri/Mandleshwar/Maheshwar', 'Maheshwar', 'Dr. Aashish Rathore', '', ''),
(180, 'Dhamnod/Dharampuri', 'Dhamnod/Dharampuri/Mandleshwar/Maheshwar', 'Maheshwar', 'Dr. Aayushi Rathore', '', ''),
(181, 'Dhamnod/Dharampuri', 'Dhamnod/Dharampuri/Mandleshwar/Maheshwar', 'Maheshwar', 'Dr. B. L. Lachheta', '', ''),
(182, 'Mhow', 'Mhow', 'Mhow', 'Dr. M. K. Tiwari', 'MS', ''),
(183, 'Mhow', 'Mhow', 'Mhow', 'Dr. P. R. Sule', '', ''),
(184, 'Mhow', 'Mhow', 'Mhow', 'Dr. Tanmay Maheshwari', 'MS', ''),
(185, 'Mhow', 'Mhow', 'Mhow', 'Dr. Neeraj Agrawal', '', ''),
(186, 'Mhow', 'Mhow', 'Mhow', 'Dr. Aamir Jouhar', 'MS ortho.', ''),
(187, 'Mhow', 'Mhow', 'Mhow', 'Mrs. R. Jouhar', 'DGO', ''),
(188, 'Mhow', 'Mhow', 'Mhow', 'Dr. L. S. Varma', '', ''),
(189, 'Mhow', 'Mhow', 'Mhow', 'Dr. Anupam Tiwari', 'MS', ''),
(190, 'Mhow', 'Mhow', 'Mhow', 'Dr. Sourabh Tilwankar', 'MS', ''),
(191, 'Mhow', 'Mhow', 'Mhow', 'Dr. Swati Agrawal', 'MD', ''),
(192, 'Mhow', 'Mhow', 'Mhow', 'Dr. Prakhar Agrawal', 'MD', ''),
(193, 'Mhow', 'Mhow', 'Mhow', 'Dr. Kunal Mewada', 'MS', ''),
(194, 'Mhow', 'Mhow', 'Mhow', 'Dr. Rahul Mewada', 'MS', ''),
(195, 'Mhow', 'Mhow', 'Mhow', 'Dr. V. K. Saxsena', 'MD', ''),
(196, 'Burhanpur', 'Burhanpur', 'Burhanpur', 'Dr. Tanveer Ginwal', '', ''),
(197, 'Burhanpur', 'Burhanpur', 'Burhanpur', 'Dr. Raj Bhat', '', ''),
(198, 'Burhanpur', 'Burhanpur', 'Burhanpur', 'Dr. Ganesh Kharche', '', ''),
(199, 'Burhanpur', 'Burhanpur', 'Burhanpur', 'Dr. Ashok Pagare', '', ''),
(200, 'Burhanpur', 'Burhanpur', 'Burhanpur', 'Dr. Ramesh Kapadiya', '', ''),
(201, 'Burhanpur', 'Burhanpur', 'Burhanpur', 'Dr. Hemant Mahajan', '', ''),
(202, 'Burhanpur', 'Burhanpur', 'Burhanpur', 'Dr. I. L. Mundra', '', ''),
(203, 'Burhanpur', 'Burhanpur', 'Burhanpur', 'Dr. Rafat Ansari', '', ''),
(204, 'Burhanpur', 'Burhanpur', 'Shahpur', 'Dr. Suresh Patil', '', ''),
(205, 'Burhanpur', 'Burhanpur', 'Shahpur', 'Dr. Dipak Patil', '', ''),
(206, 'Burhanpur', 'Burhanpur', 'Shahpur', 'Dr. Manish D. Patil', '', ''),
(207, 'Burhanpur', 'Burhanpur', 'Shahpur', 'Dr. Eshvar Mahajan', '', ''),
(208, 'Burhanpur', 'Burhanpur', 'Shahpur', 'Dr. Jagdish Patil', '', ''),
(209, 'Burhanpur', 'Burhanpur', 'Shahpur', 'Dr. Swapnil Patil', '', ''),
(210, 'Burhanpur', 'Burhanpur', 'Burhanpur', 'Dr. Ashwini Garkal', '', ''),
(211, 'Sanawad', 'Sanawad', 'Sanawad', 'Dr. Aarif Khan', '', ''),
(212, 'Sanawad', 'Sanawad', 'Sanawad', 'Dr. Iqbal Khan', '', ''),
(213, 'Sanawad', 'Sanawad', 'Sanawad', 'Dr. Ajay Adhikari', 'MD', ''),
(214, 'Sanawad', 'Sanawad', 'Sanawad', 'Dr. K. K. Shriwastwa', 'MS', ''),
(215, 'Sanawad', 'Sanawad', 'Sanawad', 'Dr. Vandana Adhikari', 'MS', ''),
(216, 'Sanawad', 'Sanawad', 'Sanawad', 'Dr. Mahesh Chouhan', '', ''),
(217, 'Sanawad', 'Sanawad', 'Sanawad', 'Dr. Aashish Sohani', '', ''),
(218, 'Sanawad', 'Sanawad', 'Sanawad', 'Dr. Sonal Pagare', 'MD', ''),
(219, 'Sanawad', 'Sanawad', 'Sanawad', 'Dr. Rahul Agrawal', 'MD', ''),
(220, 'Sanawad', 'Sanawad', 'Sanawad', 'Dr. Prakash Jain', '', ''),
(221, 'Khargone', 'Khargone/Kasrawad', 'Kasrawad', 'Dr. Chandresh Dixit', '', ''),
(222, 'Khargone', 'Khargone/Kasrawad', 'Kasrawad', 'Dr. Hemendra Patidar', '', ''),
(223, 'Khargone', 'Khargone/Kasrawad', 'Khargone', 'Dr. G. P. Gupta', 'MS', ''),
(224, 'Khargone', 'Khargone/Kasrawad', 'Khargone', 'Dr. Srashti Shah', 'MS', ''),
(225, 'Khargone', 'Khargone/Kasrawad', 'Khargone', 'Dr. Kanhaiya Yadav', 'MS ortho', ''),
(226, 'Khargone', 'Khargone/Kasrawad', 'Khargone', 'Dr. D. S. Soulanki', 'MS', ''),
(227, 'Khargone', 'Khargone/Kasrawad', 'Khargone', 'Dr. Mansukh Vishal Jaiswal', '', 'endo. And colon. Sono. Leb'),
(228, 'Khargone', 'Khargone/Kasrawad', 'Khargone', 'Dr. Pankaj Mahajan', 'MS', ''),
(229, 'Khargone', 'Khargone/Kasrawad', 'Khargone', 'Dr. Govind Gupta', 'MS', ''),
(230, 'Khargone', 'Khargone/Kasrawad', 'Khargone', 'Dr. Ajay Jain', 'MS', ''),
(231, 'Khargone', 'Khargone/Kasrawad', 'Khargone', 'Dr. Vijay Patidar', 'MS', ''),
(232, 'Khargone', 'Khargone/Kasrawad', 'Khargone', 'Dr. Gourav Patidar', 'MS', ''),
(233, 'Khargone', 'Khargone/Kasrawad', 'Khargone', 'Dr. Jainul Malik', 'MS', '');

CREATE TABLE IF NOT EXISTS visits (
  id SERIAL PRIMARY KEY,
  doctor_id INTEGER REFERENCES doctors(id),
  visit_date DATE,
  visit_time TEXT,
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS keyvalue (key TEXT PRIMARY KEY, value JSONB, shared BOOLEAN);
